-- Author: Lean Tools MCP Contributors
-- Contact: wangziyu-edu@stu.pku.edu.cn; optsuite@lean-tools-mcp
-- License: MIT

/-
havelet-generator (lake exe 版本，避开 .ofFVar(Id)Info 以及 ti.expr? / ti.lctx? 差异)
==================================================================================

用 `lake exe` 提取某 Lean 源文件中的所有局部 `have/let`，
并在指定路径生成一个独立 `.lean` 文件，包含闭合后的顶层 `def/theorem`。

用法：
  lake exe havelet_generator <input.lean> <out/Extracted.lean> <Prefix>

把下面这段代码拆成两个文件：
  1) HaveLet/Extract.lean   —— 核心抽取与生成
  2) Main.lean              —— 可执行入口 (lake exe havelet_generator)

并准备最小 lakefile.lean（在文末提供一个参考）。
-/

import Lean
import Lean.Util.Path
import HaveletGenerator.Emit

open Lean
open Lean Meta
open Lean Elab
open System

/-- 由 header 的 imports 生成文件头；若为空，降级为 `import Init` -/
def headerFromImports (imports : Array Name) (ns? : Option Name := some `Extracted) : String :=
  let imps :=
    if imports.isEmpty then
      "import Init\n\n"
    else
      String.join (imports.toList.map (fun n => s!"import {n}\n")) ++ "\n"
  match ns? with
  | some ns => s!"{imps}namespace {ns}\n\n/-! Auto-generated by HaveLetExtractor. Do not edit by hand. -/\n\n"
  | none    => s!"{imps}/-! Auto-generated by HaveLetExtractor. Do not edit by hand. -/\n\n"

/-- 提取 header 里的 import 名字 -/
private def importsFromHeader (header : TSyntax ``Lean.Parser.Module.header) : Array Name :=
  match header with
  | `(Lean.Parser.Module.header| $[module%$m?]? $[prelude]? $importsStx*) =>
      importsStx.foldl
        (init := #[])
        (fun acc stx =>
          match stx with
          | `(Lean.Parser.Module.import| $[public%$pub?]? $[meta%$meta?]? import $[all%$all?]? $mod) =>
              acc.push mod.getId
          | _ => acc)
  | _ => #[]

/-- 根据文件路径（结合搜索路径）推测模块名。 -/
private def moduleNameFromPath (pathStr : String) : IO (Option Name) := do
  let fp := System.FilePath.mk pathStr
  if fp.extension != some "lean" then
    return none

  -- 优先使用 LEAN_SRC_PATH / sysroot 中的搜索路径来反推模块名
  let srcSp ← Lean.getSrcSearchPath
  if let some mod ← Lean.searchModuleNameOfFileName fp srcSp then
    return some mod

  -- 兜底：若文件位于当前目录树下，则退化为相对路径推导
  try
    return some (← Lean.moduleNameOfFileName fp none)
  catch _ =>
    return none

/-- 向 imports 里追加一个模块（若尚未存在）。 -/
private def pushIfNew (imports : Array Name) (n : Name) : Array Name :=
  if imports.contains n then imports else imports.push n

/--
`lake exe havelet_generator <input.lean> <out/Extracted.lean> <Prefix>`
- 解析 + 处理 header
- 用 `Elab.IO.processCommands` 跑整文件，拿到 `env` 与 `InfoTree`
- 在 `MetaM` 中调用 `HaveLet.buildFile` 生成文本
- 写入目标文件
-/
def main (args : List String) : IO UInt32 := do
  match args with
  | [inFile, outFile, pref] =>

    -- 初始化搜索路径
    let _ ← Lean.initSearchPath (← Lean.findSysroot)

    -- 输入上下文
    let input    ← IO.FS.readFile inFile
    let fileName := inFile
    let inputCtx := Parser.mkInputContext input fileName

    -- 解析与处理 header
    let opts : Options := ({} : Options).setBool `saveInfo true
    let (header, parserState, messages0) ← Parser.parseHeader inputCtx
    let (envBefore, messages1)           ← Elab.processHeader header opts messages0 inputCtx

    -- 初始命令态，并开启 InfoTree
    let cmdState0 : Elab.Command.State := Elab.Command.mkState envBefore messages1 opts
    let cmdState  : Elab.Command.State := { cmdState0 with infoState := { enabled := true } }

    -- 跑所有命令
    let st        ← Elab.IO.processCommands inputCtx parserState cmdState
    let treesPA   := st.commandState.infoState.trees  -- PersistentArray InfoTree
    let trees     := treesPA.toArray                   -- 转为 Array InfoTree

    let baseImports := importsFromHeader header
    let imports ←
      match (← moduleNameFromPath inFile) with
      | some self => pure (pushIfNew baseImports self)
      | none      => pure baseImports
    let headerStr := headerFromImports imports

    let txt ← HaveLet.buildFile trees pref headerStr
    let outFP := System.FilePath.mk outFile
    match outFP.parent with
    | some p => IO.FS.createDirAll p
    | none   => pure ()
    IO.FS.writeFile outFile txt
    IO.println s!"[havelet_generator] wrote {outFile}"
    pure 0

  | _ =>
    IO.eprintln "usage: lake exe havelet_generator <input.lean> <out/Extracted.lean> <Prefix>"
    pure 2
