-- Contact: wangziyu-edu@stu.pku.edu.cn; optsuite@lean-tools-mcp
-- License: MIT

/-
havelet-generator (`lake exe` version, avoiding `.ofFVar(Id)Info` and
`ti.expr?` / `ti.lctx?` compatibility differences)
==================================================================================

Use `lake exe` to extract all local `have/let` bindings from a Lean source file
and generate a standalone `.lean` file containing closed top-level `def/theorem`s.

Usage:
  lake exe havelet_generator <input.lean> <out/Extracted.lean> <Prefix>

This implementation is split across two files:
  1) HaveLet/Extract.lean   -- core extraction and generation logic
  2) Main.lean              -- executable entry point (`lake exe havelet_generator`)

It also expects a minimal `lakefile.lean` (a sample is provided near the end).
-/

import Lean
import Lean.Util.Path
import HaveletGenerator.Emit

open Lean
open Lean Meta
open Lean Elab
open System

/-- Build the generated file header from header imports, falling back to `import Init` if empty. -/
def headerFromImports (imports : Array Name) (ns? : Option Name := some `Extracted) : String :=
  let imps :=
    if imports.isEmpty then
      "import Init\n\n"
    else
      String.join (imports.toList.map (fun n => s!"import {n}\n")) ++ "\n"
  match ns? with
  | some ns => s!"{imps}namespace {ns}\n\n/-! Auto-generated by HaveLetExtractor. Do not edit by hand. -/\n\n"
  | none    => s!"{imps}/-! Auto-generated by HaveLetExtractor. Do not edit by hand. -/\n\n"

/-- Extract import names from the parsed header. -/
private def importsFromHeader (header : TSyntax ``Lean.Parser.Module.header) : Array Name :=
  match header with
  | `(Lean.Parser.Module.header| $[module%$m?]? $[prelude]? $importsStx*) =>
      importsStx.foldl
        (init := #[])
        (fun acc stx =>
          match stx with
          | `(Lean.Parser.Module.import| $[public%$pub?]? $[meta%$meta?]? import $[all%$all?]? $mod) =>
              acc.push mod.getId
          | _ => acc)
  | _ => #[]

/-- Infer the module name from a file path, using the search path when possible. -/
private def moduleNameFromPath (pathStr : String) : IO (Option Name) := do
  let fp := System.FilePath.mk pathStr
  if fp.extension != some "lean" then
    return none

  -- Prefer reconstructing the module name from LEAN_SRC_PATH / sysroot search paths.
  let srcSp ← Lean.getSrcSearchPath
  if let some mod ← Lean.searchModuleNameOfFileName fp srcSp then
    return some mod

  -- Fallback: if the file is under the current directory tree, derive the module name relatively.
  try
    return some (← Lean.moduleNameOfFileName fp none)
  catch _ =>
    return none

/-- Append a module to `imports` if it is not already present. -/
private def pushIfNew (imports : Array Name) (n : Name) : Array Name :=
  if imports.contains n then imports else imports.push n

/--
`lake exe havelet_generator <input.lean> <out/Extracted.lean> <Prefix>`
- Parse and process the header
- Run the whole file through `Elab.IO.processCommands` to obtain `env` and `InfoTree`
- Call `HaveLet.buildFile` inside `MetaM` to generate the output text
- Write the target file
-/
def main (args : List String) : IO UInt32 := do
  match args with
  | [inFile, outFile, pref] =>

    -- Initialize the search path.
    let _ ← Lean.initSearchPath (← Lean.findSysroot)

    -- Input context.
    let input    ← IO.FS.readFile inFile
    let fileName := inFile
    let inputCtx := Parser.mkInputContext input fileName

    -- Parse and process the file header.
    let opts : Options := ({} : Options).setBool `saveInfo true
    let (header, parserState, messages0) ← Parser.parseHeader inputCtx
    let (envBefore, messages1)           ← Elab.processHeader header opts messages0 inputCtx

    -- Initial command state with InfoTree collection enabled.
    let cmdState0 : Elab.Command.State := Elab.Command.mkState envBefore messages1 opts
    let cmdState  : Elab.Command.State := { cmdState0 with infoState := { enabled := true } }

    -- Process all commands.
    let st        ← Elab.IO.processCommands inputCtx parserState cmdState
    let treesPA   := st.commandState.infoState.trees  -- `PersistentArray InfoTree`
    let trees     := treesPA.toArray                   -- Convert to `Array InfoTree`.

    let baseImports := importsFromHeader header
    let imports ←
      match (← moduleNameFromPath inFile) with
      | some self => pure (pushIfNew baseImports self)
      | none      => pure baseImports
    let headerStr := headerFromImports imports

    let txt ← HaveLet.buildFile trees pref headerStr
    let outFP := System.FilePath.mk outFile
    match outFP.parent with
    | some p => IO.FS.createDirAll p
    | none   => pure ()
    IO.FS.writeFile outFile txt
    IO.println s!"[havelet_generator] wrote {outFile}"
    pure 0

  | _ =>
    IO.eprintln "usage: lake exe havelet_generator <input.lean> <out/Extracted.lean> <Prefix>"
    pure 2
